name: Deploy on push to staging server

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{secrets.DEPLOY_SERVER_NAME}}
        username: ${{secrets.DEPLOY_SERVER_USERNAME}}
        password: ${{secrets.DEPLOY_SERVER_PASSWORD}}
        server-dir: '/public_html/'
        port: 21
        protocol: ftps
